### ISSUE TITLE
Crash On Precise

### ISSUE THREAD

**Issue by thisisprateeksaxena** [brtmr/podfox#13]
After install, I tried:

podfox import http://feeds.feedburner.com/techsnapmp3

It gave me the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/podfox", line 11, in <module>
    load_entry_point('podfox==0.1.2', 'console_scripts', 'podfox')()
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 564, in load_entry_point
    
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 2608, in load_entry_point
    
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 2268, in load
    
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 2274, in resolve
    
  File "/usr/local/lib/python2.7/dist-packages/podfox/__init__.py", line 52
    Fore.RESET + Back.RESET + Style.RESET_ALL, file=sys.stderr)

**Comment by tmajibon** [comment]
That appears to be missing the final line which gives the error message.

**Comment by tmajibon** [comment]
Including error message from another user which matches the circumstance:

> Traceback (most recent call last):
>   File "/usr/local/bin/podfox", line 9, in <module>
>     load_entry_point('podfox==0.1.1', 'console_scripts', 'podfox')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/podfox-0.1.1-py2.7.egg/podfox/__init__.py", line 52
>     Fore.RESET + Back.RESET + Style.RESET_ALL, file=sys.stderr)
>                                                    ^
> SyntaxError: invalid syntax

**Comment by tmajibon** [comment]
I just noticed that in both cases it lists python2.7, but podfox is programmed for python3.

Could you try removing it and re-installing with python3?
