### ISSUE TITLE
Error with pip install

### ISSUE THREAD

**Issue by Pacit0** [brtmr/podfox#14]
Hi,

I just try to install podfox and I have this error, do you know how I can solve it?
```podcastuser@myserver:~$ pip install podfox
Downloading/unpacking podfox
  Downloading podfox-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip-build-JLFnjG/podfox/setup.py) egg_info for package podfox
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-JLFnjG/podfox/setup.py", line 3, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-JLFnjG/podfox/setup.py", line 3, in <module>

    with open('requirements.txt') as f:

IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-JLFnjG/podfox
Storing debug log for failure in /home/podcastuser/.pip/pip.log```

Thanks in advance!

**Comment by tmajibon** [comment]
Looks like the requirements.txt file was missing when the egg was was built.

While I can't fix it (it's a repository rather than a code issue), you should be able to install from source files just fine.

**Comment by Pacit0** [comment]
Thanks for your answer! I installed podfox with the source but now I get this error by import:

```
podcastuser@xxx:~$ podfox import http://radiofrance-podcast.net/podcast09/rss_14522.xml nora_hamzawi
Traceback (most recent call last):
  File "/usr/local/bin/podfox", line 9, in <module>
    load_entry_point('podfox==0.1.1', 'console_scripts', 'podfox')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/podfox-0.1.1-py2.7.egg/podfox/__init__.py", line 52
    Fore.RESET + Back.RESET + Style.RESET_ALL, file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
´´´

Thanks

**Comment by tmajibon** [comment]
#13 
Looks like you just added the line the other guy was missing from his post.

I would recommend subscribing to that issue for updates, though I have one thought already:

Podfox is programmed for python3 and the error indicates that it's running in python2.7, could you try removing it and re-installing with python3?

**Comment by Pacit0** [comment]
The installation worked fine with python3!
I created the podfox configuration file but it still doesn't work

```
podcastuser@xxx:~$ podfox import http://radiofrance-podcast.net/podcast09/rss_14522.xml nora_hamzawi
Traceback (most recent call last):
  File "/usr/local/bin/podfox", line 9, in <module>
    load_entry_point('podfox==0.1.1', 'console_scripts', 'podfox')()
  File "/usr/local/lib/python3.4/dist-packages/podfox-0.1.1-py3.4.egg/podfox/__init__.py", line 300, in main
    shortname=arguments['<shortname>'])
  File "/usr/local/lib/python3.4/dist-packages/podfox-0.1.1-py3.4.egg/podfox/__init__.py", line 86, in import_feed
    folder = get_folder(shortname)
  File "/usr/local/lib/python3.4/dist-packages/podfox-0.1.1-py3.4.egg/podfox/__init__.py", line 60, in get_folder
    base = CONFIGURATION['podcast-directory']
KeyError: 'podcast-directory'
podcastuser@xxx:~$ cat .podfox.json 
{
    "podcast-directory" : "/home/podcastuser/podcasts",
    "maxnum"            : 5
}
´´´

Thanks

**Comment by tmajibon** [comment]
Please copy this to a new issue so that it can be tracked properly.
