### ISSUE TITLE
Dependencies upgrade

### ISSUE THREAD

**Issue by isakrubin** [brtmr/podfox#38]
Any plans for an upgrade to support feedparser > 5.2.1 ?

`Collecting feedparser
  Downloading feedparser-6.0.2-py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 2.9 MB/s
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Using legacy setup.py install for sgmllib3k, since package 'wheel' is not installed.
ERROR: podfox 0.1.2 has requirement feedparser==5.2.1, but you'll have feedparser 6.0.2 which is incompatible.
Installing collected packages: sgmllib3k, feedparser
    Running setup.py install for sgmllib3k ... done
  Attempting uninstall: feedparser
    Found existing installation: feedparser 5.2.1
    Uninstalling feedparser-5.2.1:
      Successfully uninstalled feedparser-5.2.1
Successfully installed feedparser-6.0.2 sgmllib3k-1.0.0
`

Feedparser 5.2.1 have issues with python3.9

`Traceback (most recent call last):
  File "/home/x/podfox_env/bin/podfox", line 5, in <module>
    from podfox.__init__ import main
  File "/home/x/podfox_env/lib/python3.9/site-packages/podfox/__init__.py", line 25, in <module>
    import feedparser
  File "/home/x/podfox_env/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
`

**Comment by bingalls** [comment]
Not a direct solution, but https://github.com/alixnovosi/puckfetcher supports Python 3.9. HTH

**Comment by zachyordy** [comment]
Seems like the base64 module was deprecated in python 3.9. To solve this problem, I just ended up installing python 3.8, pip installing podfox inside of a venv (that used the python 3.8 binary), and symlinking /usr/local/bin/podfox to the podfox binary inside of the venv. This works well for me for now!

**Comment by palortoff** [comment]
As python 3.8 was not an option for me I installed `feedparser==6.0.8` into my podfox venv.

This also fixed podfox for me.

Updated dependencies would be nice though...
