### ISSUE TITLE
KeyError: 'maxage-days'

### ISSUE THREAD

**Issue by ben-rowan** [brtmr/podfox#49]
On a fresh install of podfox with the recommended config in my local .podfox.json I get the following error when I try to download an episode:

```
$ podfox download jupiter
Traceback (most recent call last):
  File "/home/ben/PythonEnvs/podfox_env/bin/podfox", line 33, in <module>
    sys.exit(load_entry_point('podfox==0.1.1', 'console_scripts', 'podfox')())
  File "/home/ben/PythonEnvs/podfox_env/lib/python3.9/site-packages/podfox-0.1.1-py3.9.egg/podfox/__init__.py", line 401, in main
    download_multiple(feed, maxnum)
  File "/home/ben/PythonEnvs/podfox_env/lib/python3.9/site-packages/podfox-0.1.1-py3.9.egg/podfox/__init__.py", line 227, in download_multiple
    if not episode['downloaded'] and not episode_too_old(episode, CONFIGURATION['maxage-days']):
KeyError: 'maxage-days'
```

It looks like `maxage-days` is missing from the default config. If I add `maxage-days` to my local config the download works fine. I've created a small change to fix this and I'll create a pull request for it shortly.

**Comment by zevaverbach** [comment]
might be time to hard fork this puppy! thanks for your PRs, @ben-rowan, I'm benefiting currently from the `setuptools`-related one.
